version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: git reset --hard HEAD
      - run: git checkout dev
      - run: git config user.email "scala1117@gmail.com"
      - run: git config user.name "hiroki1117"
      - run: git checkout master
      - run: git merge dev
      - run: git push